--=============================================================================================================================================================================================
--============= DATA_INSERTION_PROCEDURES.sql =================================================================================================================================================
--============= Contém SP's utilizadas na insersão de dados em diversas tabelas (insersões que envolvam mais que uma tabela em simultâneo), por parte do utilizador. ==========================
--=============================================================================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--STORED PROCEDURE PARA A INSERSÃO DE MISSÕES ESPACIAIS LOGISTICAS NA TABELA 'SPACE_LOGISTICS'
CREATE PROCEDURE SP_INSERT_SPACE_LOGISTICS
@MISSION_NAME varchar(100),
@MISSION_TYPE_ID int,
@MISSION_COMPANY_ID int,
@MISSION_TRANSPORT_VEHICLE_ID int,
@DESCRIPTION text,
@LAUNCH_DATE date,
@LANDING_DATE date,
@LAUNCH_LOCATION varchar(50),
@LANDING_LOCATION varchar(50),
@BUDGET float
AS
BEGIN
	INSERT INTO OPERATION_LOGS(OPERATION_NAME, OPERATION_CATEGORY_ID, OPERATION_STATUS_ID) VALUES('SP_LG-' + @MISSION_NAME, 1, 1) --INSERSÃO DA OPERAÇÃO A QUE ESTA MISSÃO ESTÁ ASSOCIADA (REFERENCIA NA TABELA OPERATION_LOGS)
	DECLARE @LAST_OPERATION_ID INT;
	SET	@LAST_OPERATION_ID = (SELECT MAX(OPERATION_LOGS.OPERATION_ID) FROM OPERATION_LOGS);

	--INSERSÃO DA MISSÃO NA TABELA SPACE_LOGISTICS
	INSERT INTO SPACE_LOGISTICS(OPERATION_ID, MISSION_NAME, MISSION_TYPE_ID, MISSION_COMPANY_ID, MISSION_TRANSPORT_VEHICLE_ID, DESCRIPTION, LAUNCH_DATE, LANDING_DATE, LAUNCH_LOCATION, LANDING_LOCATION, BUDGET) VALUES(@LAST_OPERATION_ID,
	@MISSION_NAME,
	@MISSION_TYPE_ID,
	@MISSION_COMPANY_ID,
	@MISSION_TRANSPORT_VEHICLE_ID,
	@DESCRIPTION,
	@LAUNCH_DATE,
	@LANDING_DATE,
	@LAUNCH_LOCATION,
	@LANDING_LOCATION,
	@BUDGET)
END

GO

--STORED PROCEDURE PARA INSERSÃO DE VEÍCULOS, NA TABELA 'VEHICLES'
CREATE PROCEDURE SP_INSERT_VEHICLES
@VEHICLE_SERIAL_NUMBER varchar(50),
@VEHICLE_MANUFACTURER_ID int,
@VEHICLE_PRODUCTION_DATE date,
@VEHICLE_NAME varchar(100),
@VEHICLE_TYPE_ID int,
@VEHICLE_MASS float,
@VEHICLE_LENGTH float,
@VEHICLE_WIDTH float,
@VEHICLE_HEIGHT float,
@VEHICLE_FUEL_TYPE_ID int,
@VEHICLE_NEXT_MAINTENANCE_DATE date
AS
BEGIN
	--INSERSÃO DO VEÍCULO, NA TABELA 'VEHICLES'
	INSERT INTO VEHICLES(VEHICLE_SERIAL_NUMBER, VEHICLE_MANUFACTURER_ID, VEHICLE_PRODUCTION_DATE, VEHICLE_NAME, VEHICLE_TYPE_ID, VEHICLE_MASS, VEHICLE_LENGTH, VEHICLE_WIDTH, VEHICLE_HEIGHT, VEHICLE_FUEL_TYPE_ID, VEHICLE_NEXT_MAINTENANCE_DATE) VALUES (
	@VEHICLE_SERIAL_NUMBER,
	@VEHICLE_MANUFACTURER_ID,
	@VEHICLE_PRODUCTION_DATE,
	@VEHICLE_NAME,
	@VEHICLE_TYPE_ID,
	@VEHICLE_MASS,
	@VEHICLE_LENGTH,
	@VEHICLE_WIDTH,
	@VEHICLE_HEIGHT,
	@VEHICLE_FUEL_TYPE_ID,
	@VEHICLE_NEXT_MAINTENANCE_DATE);
END

GO

--PROCEDURE PARA INSERSÃO DE CENTRAL ELÉTRICA NA TABELA 'POWER_PLANTS'. DURANTE ESSA INSERSÃO, ESTA É TAMBÉM ASSOCIADA Á(S) CIDADE(S) ALIMENTADA(S) POR SI
CREATE PROCEDURE SP_INSERT_POWER_PLANTS
@POWER_PLANT_NAME varchar(50),
@POWER_PLANT_COMPANY_ID int,
@POWER_PLANT_TYPE_ID int,
@POWER_PLANT_LOCATION varchar(100),
@POWER_PLANT_MAX_OUTPUT_CAPACITY float,
@POWER_PLANT_STATUS_ID int,
@POWER_PLANT_NEXT_MAINTENANCE_DATE date,
@POWER_PLANT_INSTALLATION_DATE date,
@TARGET_CITIES_ID varchar(20)
AS
BEGIN
	--=======================================================================================================================================================================================================================
	--INSERSÃO DA CENTRAL ELÉTRICA NA TABELA POWER_PLANTS
	INSERT INTO POWER_PLANTS(POWER_PLANT_NAME, POWER_PLANT_COMPANY_ID, POWER_PLANT_TYPE_ID, POWER_PLANT_LOCATION, POWER_PLANT_MAX_OUTPUT_CAPACITY, POWER_PLANT_STATUS_ID, POWER_PLANT_NEXT_MAINTENANCE_DATE, POWER_PLANT_INSTALLATION_DATE) VALUES(
	@POWER_PLANT_NAME,
	@POWER_PLANT_COMPANY_ID,
	@POWER_PLANT_TYPE_ID,
	@POWER_PLANT_LOCATION,
	@POWER_PLANT_MAX_OUTPUT_CAPACITY,
	@POWER_PLANT_STATUS_ID,
	@POWER_PLANT_NEXT_MAINTENANCE_DATE,
	@POWER_PLANT_INSTALLATION_DATE)

	--=======================================================================================================================================================================================================================

	DECLARE @_POWER_PLANT_ID INT; --ID DA CENTRAL ELÉTRICA INSERIDA
	SET @_POWER_PLANT_ID = (SELECT MAX(POWER_PLANT_ID) FROM POWER_PLANTS) --A CENTRAL INSERIDA VAI TER O MAIOR ID DA TABELA (É A MAIS RECENTE)

	DECLARE @TARGET_CITIES_TEMP_TABLE TABLE(splited_str varchar(4)) --TABELA TEMPORARIA PARA GUARDAR OS ID's DAS CIDADES A CONECTAR Á CENTRAL
	INSERT INTO @TARGET_CITIES_TEMP_TABLE(splited_str)	(SELECT [value] FROM STRING_SPLIT(@TARGET_CITIES_ID, ',')); --CONVERSÃO DE VARCHAR(20) PARA TABLE (SPLIT DA STRING)

	DECLARE @I INT = 1; -- CONTADOR PARA CICLO WHILE
	WHILE @I-1 < (SELECT COUNT(*) FROM @TARGET_CITIES_TEMP_TABLE) -- ESTE CICLO VAI PERCORRER TODOS OS VALORES DA TABELA @TARGET_CITIES_TEMP_TABLE, ENQUANTO @I-1 FOR MENOR QUE O NÚMERO DE REGISTOS DESTA
	BEGIN
		DECLARE @_CITY_ID INT; --ID DA CIDADE A LIGAR Á CENTRAL ELÉTRICA
		SET @_CITY_ID = (SELECT TOP(1) CONVERT(INT, splited_str) FROM @TARGET_CITIES_TEMP_TABLE WHERE @I = CONVERT(INT, splited_str))

		INSERT INTO CITY_REL_POWERPLANTS(CITY_ID, CITY_ENERGY_SOURCE_ID) VALUES(@_CITY_ID, @_POWER_PLANT_ID) --INSERSÃO DA LIGAÇÃO DA CIDADE COM A CENTRAL ELÉTRICA, NA TABELA QUE AS RELACIONA (CITY_REL_POWERPLANTS)
		SET @I = @I + 1 --INCREMENTO DO CONTADOR @I
	END
	--=======================================================================================================================================================================================================================
END
/*EXEMPLO DE EXECUÇÃO:
EXEC SP_INSERT_POWER_PLANTS @POWER_PLANT_NAME = 'AAAAA',
@POWER_PLANT_COMPANY_ID = 1,
@POWER_PLANT_TYPE_ID = 1,
@POWER_PLANT_LOCATION = 'LOCATION3301',
@POWER_PLANT_MAX_OUTPUT_CAPACITY = 20000,
@POWER_PLANT_STATUS_ID = 1,
@POWER_PLANT_NEXT_MAINTENANCE_DATE = '1990-09-09',
@POWER_PLANT_INSTALLATION_DATE = '1990-09-09',
@TARGET_CITIES_ID = '1,2,3'
*/