USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--ESTE SELECT LISTA OS DADOS DE CADA UTILIZADOR (DA VIEW 'VW_USER_CARACTERISTICS') ORDENADOS PELA DATA DE NASCIMENTO ASCENDENTEMENTE;
SELECT * FROM VW_USER_CARACTERISTICS (NOLOCK) ORDER BY USER_BIRTHDATE ASC;
GO

--ESTE SELECT LISTA OS DADOS DE CADA VEÍCULO (DA VIEW 'VW_SCIENTIFIC_PROSPECTION_DATA') ONDE O 'TASK_TYPE_NAME' É 'Atmospheric Research' E O 'VEHICLE_NAME' COMECA PELA LETRA 'A';
SELECT * FROM VW_SCIENTIFIC_PROSPECTION_DATA (NOLOCK) WHERE TASK_TYPE_NAME = 'Atmospheric Research' AND VEHICLE_NAME LIKE ('A%');
GO

--ESTE SELECT CONTÉM OS DADOS DE CADA MÁQUINA (DA VIEW 'MACHINES') ORDENADA PELO 'MACHINE_STATUS_NAME' DESCENDENTEMENTE, SENDO SOMENTE LISTADO O PRIMEIRO REGISTO;
SELECT TOP(1) * FROM MACHINES (NOLOCK) ORDER BY MACHINE_STATUS_NAME DESC;
GO

--ESTE SELECT CALCULA A TAXA DE DESPERDICIO DE ENERGIA DE CADA CENTRAL, ORDENANDO OS VALORES POR ORDEM CRESCENTE DE TAXA DE DESPERDÍCIO.
WITH SUBQUERY1 AS (SELECT dbo.FN_ENERGY_PRODUCTION_LAST_MONTH(POWER_PLANT_ID, MONTH(GETDATE())) AS ENERGY_PRODUCTION, dbo.FN_ENERGY_CONSUMPTION_LAST_MONTH(POWER_PLANT_ID, MONTH(GETDATE())) AS ENERGY_CONSUMPTION, dbo.FN_ENERGY_STORAGE_LAST_MONTH(POWER_PLANT_ID, MONTH(GETDATE())) AS ENERGY_STORAGE FROM VW_POWER_FLUX_LOGS (NOLOCK))
SELECT SUBQUERY1.ENERGY_PRODUCTION, FN_CALC_WASTED_ENERGY(SUBQUERY1.ENERGY_PRODUCTION, SUBQUERY1.ENERGY_CONSUMPTION, SUBQUERY1.ENERGY_STORAGE) FROM SUBQUERY1
SELECT POWER_PLANT_ID, POWER_PLANT_NAME FROM VW_POWER_FLUX_LOGS (NOLOCK) GROUP BY POWER_PLANT_ID