USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--ESTE SELECT LISTA OS DADOS DE CADA VEÍCULO (DA VIEW 'VW_SCIENTIFIC_PROSPECTION_DATA') ONDE O 'TASK_TYPE_NAME' É 'Atmospheric Research' E O 'VEHICLE_NAME' COMECA PELA LETRA 'A';
SELECT * FROM VW_SCIENTIFIC_PROSPECTION_DATA (NOLOCK) WHERE TASK_TYPE_NAME = 'Atmospheric Research' AND VEHICLE_NAME LIKE ('A%');
GO

--ESTE SELECT CONTÉM OS DADOS DE CADA MÁQUINA (DA VIEW 'MACHINES') ORDENADA PELO 'MACHINE_STATUS_NAME' DESCENDENTEMENTE, SENDO SOMENTE LISTADO O PRIMEIRO REGISTO;
SELECT TOP(1) * FROM VEHICLES (NOLOCK) ORDER BY VEHICLE_NAME DESC;