USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--UTILIZADORES
--QUERY PARA LISTAR OS ADMINISTRADORES (TÊM DIREITOS TOTAIS DE EDIÇÃO E GESTÃO DA BD) DA PLATAFORMA
SELECT USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_PHONENUMBER, USER_PROFILE_PICTURE_PATH, USER_BIRTHDATE, USER_GENDER_NAME, COUNTRY_NAME, USER_ADRESS, USER_JOB_NAME, USER_ACADEMIC_LEVEL_NAME, USER_LEVEL_NAME FROM VW_USER_CARACTERISTICS (NOLOCK) WHERE USER_LEVEL_NAME = 'ADMINISTRATOR'
--QUERY PARA LISTAR OS PROGRAMADORES (TÊM DIREITOS RESTRITOS DE EDIÇÃO DA BASE DE DADOS => NÃO TÊM PERMISSÃO PARA ALTERAR AS PERMISSÕES DE OUTROS USERS, NEM PODEM REMOVER A BD) DA PLATAFORMA
SELECT USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_PHONENUMBER, USER_PROFILE_PICTURE_PATH, USER_BIRTHDATE, USER_GENDER_NAME, COUNTRY_NAME, USER_ADRESS, USER_JOB_NAME, USER_ACADEMIC_LEVEL_NAME, USER_LEVEL_NAME FROM VW_USER_CARACTERISTICS (NOLOCK) WHERE USER_LEVEL_NAME = 'DEVELOPERS'
--QUERY PARA LISTAR OS ANALISTAS DE DADOS (TÊM DIREITOS TOTAIS DE VISUALIZAÇÃO DE DADOS, EXCETO INFORMAÇÃO SENESIVEL - EX: PASSWORDS) DA PLATAFORMA
SELECT USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_PHONENUMBER, USER_PROFILE_PICTURE_PATH, USER_BIRTHDATE, USER_GENDER_NAME, COUNTRY_NAME, USER_ADRESS, USER_JOB_NAME, USER_ACADEMIC_LEVEL_NAME, USER_LEVEL_NAME FROM VW_USER_CARACTERISTICS (NOLOCK) WHERE USER_LEVEL_NAME = 'DATA_ANALYST'
--QUERY PARA LISTAR OS UTILIZADORES BASICOS (TÊM DIREITOS RESTRITOS DE VISUALIZAÇÃO DE DADOS) DA PLATAFORMA
SELECT USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_PHONENUMBER, USER_PROFILE_PICTURE_PATH, USER_BIRTHDATE, USER_GENDER_NAME, COUNTRY_NAME, USER_ADRESS, USER_JOB_NAME, USER_ACADEMIC_LEVEL_NAME, USER_LEVEL_NAME FROM VW_USER_CARACTERISTICS (NOLOCK) WHERE USER_LEVEL_NAME = 'USER'

--QUERY PARA LISTAR OS UTILIZADORES QUE SÃO CEO's DE ALGUMA EMPRESA
SELECT USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_PHONENUMBER, USER_PROFILE_PICTURE_PATH, USER_BIRTHDATE, USER_GENDER_NAME, COUNTRY_NAME, USER_ADRESS, USER_JOB_NAME, USER_ACADEMIC_LEVEL_NAME, USER_LEVEL_NAME, COMPANY_NAME, COMPANY_TYPES.COMPANY_TYPE_NAME FROM VW_USER_CARACTERISTICS INNER JOIN COMPANIES ON COMPANY_CEO_ID = USER_ID INNER JOIN COMPANY_TYPES ON COMPANIES.COMPANY_TYPE_ID = COMPANY_TYPES.COMPANY_TYPE_ID

--QUERY PARA LISTAR OS UTILIZADORES COM NIVEL ACADÉMICO SUPERIOR OU IGUAL AO MESTRADO (MASTER'S DEGREE)
SELECT USER_ID, USER_FIRST_NAME, USER_LAST_NAME, USER_EMAIL, USER_PHONENUMBER, USER_PROFILE_PICTURE_PATH, USER_BIRTHDATE, USER_GENDER_NAME, COUNTRY_NAME, USER_ADRESS, USER_JOB_NAME, USER_ACADEMIC_LEVEL_NAME, USER_LEVEL_NAME FROM VW_USER_CARACTERISTICS WHERE USER_ACADEMIC_LEVEL_ID >= 6;

--QUERY PARA CALCULAR A PERCENTAGEM DE UTILIZADORES COM NIVEL ACADÉMICO SUPERIOR OU IGUAL AO MESTRADO (MASTER'S DEGREE)
WITH SUBQUERY1 AS (SELECT COUNT(*) AS COUNT_USERS FROM VW_USER_CARACTERISTICS),
SUBQUERY2 AS (SELECT COUNT(*) AS COUNT_USERS_ABOVE_MASTERS FROM VW_USER_CARACTERISTICS WHERE USER_ACADEMIC_LEVEL_ID >= 6)
SELECT CAST(ROUND(dbo.FN_CALC_PERCENTAGE(SUBQUERY1.COUNT_USERS, SUBQUERY2.COUNT_USERS_ABOVE_MASTERS), 2) AS VARCHAR) + ' %' AS USERS_ABOVE_MASTERS_PERCENTAGE FROM SUBQUERY1 FULL JOIN SUBQUERY2 ON 1 = 1;

--QUERY PARA LISTAR
--ESTE SELECT LISTA OS DADOS DE CADA UTILIZADOR (DA VIEW 'VW_USER_CARACTERISTICS') ORDENADOS PELA DATA DE NASCIMENTO ASCENDENTEMENTE;
SELECT * FROM VW_USER_CARACTERISTICS (NOLOCK) ORDER BY USER_BIRTHDATE ASC;