--==================================================================================================================================================
--============= BUILDINGS_MGMT_VIEWS.sql ===========================================================================================================
--============= Aqui são criadas views para a obtenção de estatisticas da construção de infraestruturas. ===========================================
--==================================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

CREATE VIEW VW_BUILDINGS_FULL_INFORMATION AS (SELECT BUILDING_ID,
CITY_BUILDING_TYPES.CITY_BUILDING_TYPE_NAME,
BUILDING_NAME,
BUILDING_LOCATION,
BUILDING_HEIGHT,
BUILDING_WIDTH,
BUILDING_LENGTH,
BUILDING_POWER_CONSUMPTION,
BUILDING_CONSTRUCTION_DATE,
BUILDING_PLANT,
VW_USERS_BASIC_INFORMATION.USER_FIRST_NAME AS BUILDING_OWNER_FIRST_NAME,
VW_USERS_BASIC_INFORMATION.USER_LAST_NAME AS BUILDING_OWNER_LAST_NAME,
CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_NAME,
BUILDING_COST,
BUILDING_CITY_ID,
VW_CITIES.CITY_NAME,
VW_CITIES.PRESIDENT_FIRST_NAME AS CITY_PRESIDENT_FIRST_NAME,
VW_USERS_BASIC_INFORMATION.USER_LAST_NAME AS CITY_PRESIDENT_LAST_NAME
FROM CITY_BUILDINGS (NOLOCK)
INNER JOIN VW_CITIES ON CITY_BUILDINGS.BUILDING_CITY_ID = VW_CITIES.CITY_ID
INNER JOIN CITY_BUILDING_TYPES ON CITY_BUILDINGS.BUILDING_TYPE_ID = CITY_BUILDING_TYPES.CITY_BUILDING_TYPE_ID
INNER JOIN VW_USERS_BASIC_INFORMATION ON CITY_BUILDINGS.BUILDING_OWNER_USER_ID = VW_USERS_BASIC_INFORMATION.USER_ID
INNER JOIN CONSTRUCTION_STATUS ON CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_NAME = VW_CITIES.CITY_CONSTRUCTION_STATUS_NAME)

GO

CREATE VIEW VW_BUILDINGS_BASIC_INFORMATION AS (SELECT BUILDING_ID,
CITY_BUILDING_TYPES.CITY_BUILDING_TYPE_NAME,
BUILDING_NAME,
BUILDING_LOCATION,
BUILDING_HEIGHT,
BUILDING_WIDTH,
BUILDING_LENGTH,
BUILDING_CONSTRUCTION_DATE,
VW_USERS_BASIC_INFORMATION.USER_FIRST_NAME AS BUILDING_OWNER_FIRST_NAME,
VW_USERS_BASIC_INFORMATION.USER_LAST_NAME AS BUILDING_OWNER_LAST_NAME,
CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_NAME,
VW_CITIES.CITY_NAME
FROM CITY_BUILDINGS (NOLOCK)
INNER JOIN VW_CITIES ON CITY_BUILDINGS.BUILDING_CITY_ID = VW_CITIES.CITY_ID
INNER JOIN CITY_BUILDING_TYPES ON CITY_BUILDINGS.BUILDING_TYPE_ID = CITY_BUILDING_TYPES.CITY_BUILDING_TYPE_ID
INNER JOIN VW_USERS_BASIC_INFORMATION ON CITY_BUILDINGS.BUILDING_OWNER_USER_ID = VW_USERS_BASIC_INFORMATION.USER_ID
INNER JOIN CONSTRUCTION_STATUS ON CONSTRUCTION_STATUS.CONSTRUCTION_STATUS_NAME = VW_CITIES.CITY_CONSTRUCTION_STATUS_NAME)