--=============================================================================================================================================================================================
--============= DATA_INSERTION_PROCEDURES.sql =================================================================================================================================================
--============= Cont�m SP's utilizadas na insers�o de dados em diversas tabelas (insers�es que envolvam mais que uma tabela em simult�neo), por parte do utilizador. ==========================
--=============================================================================================================================================================================================

USE [_MORPHEUS_ENGINE_] -- DB CONNECTION
GO

--STORED PROCEDURE PARA A INSERS�O DE MISS�ES ESPACIAIS LOGISTICAS NA TABELA 'SPACE_LOGISTICS'
CREATE PROCEDURE SP_INSERT_SPACE_LOGISTICS
@MISSION_NAME varchar(100),
@MISSION_TYPE_ID int,
@MISSION_COMPANY_ID int,
@MISSION_TRANSPORT_VEHICLE_ID int,
@DESCRIPTION text,
@LAUNCH_DATE date,
@LANDING_DATE date,
@LAUNCH_LOCATION varchar(50),
@LANDING_LOCATION varchar(50),
@BUDGET float
AS
BEGIN
	INSERT INTO OPERATION_LOGS(OPERATION_NAME, OPERATION_CATEGORY_ID, OPERATION_STATUS_ID) VALUES('SP_LG-' + @MISSION_NAME, 1, 1) --INSERS�O DA OPERA��O A QUE ESTA MISS�O EST� ASSOCIADA (REFERENCIA NA TABELA OPERATION_LOGS)
	DECLARE @LAST_OPERATION_ID INT;
	SET	@LAST_OPERATION_ID = (SELECT MAX(OPERATION_LOGS.OPERATION_ID) FROM OPERATION_LOGS);

	--INSERS�O DA MISS�O NA TABELA SPACE_LOGISTICS
	INSERT INTO SPACE_LOGISTICS(OPERATION_ID, MISSION_NAME, MISSION_TYPE_ID, MISSION_COMPANY_ID, MISSION_TRANSPORT_VEHICLE_ID, DESCRIPTION, LAUNCH_DATE, LANDING_DATE, LAUNCH_LOCATION, LANDING_LOCATION, BUDGET) VALUES(@LAST_OPERATION_ID,
	@MISSION_NAME,
	@MISSION_TYPE_ID,
	@MISSION_COMPANY_ID,
	@MISSION_TRANSPORT_VEHICLE_ID,
	@DESCRIPTION,
	@LAUNCH_DATE,
	@LANDING_DATE,
	@LAUNCH_LOCATION,
	@LANDING_LOCATION,
	@BUDGET)
END

GO

--STORED PROCEDURE PARA INSERS�O DE VE�CULOS, NA TABELA 'VEHICLES'
CREATE PROCEDURE SP_INSERT_VEHICLES
@VEHICLE_SERIAL_NUMBER varchar(50),
@VEHICLE_MANUFACTURER_ID int,
@VEHICLE_PRODUCTION_DATE date,
@VEHICLE_NAME varchar(100),
@VEHICLE_TYPE_ID int,
@VEHICLE_MASS float,
@VEHICLE_LENGTH float,
@VEHICLE_WIDTH float,
@VEHICLE_HEIGHT float,
@VEHICLE_FUEL_TYPE_ID int,
@VEHICLE_NEXT_MAINTENANCE_DATE date
AS
BEGIN
	--INSERS�O DO VE�CULO, NA TABELA 'VEHICLES'
	INSERT INTO VEHICLES(VEHICLE_SERIAL_NUMBER, VEHICLE_MANUFACTURER_ID, VEHICLE_PRODUCTION_DATE, VEHICLE_NAME, VEHICLE_TYPE_ID, VEHICLE_MASS, VEHICLE_LENGTH, VEHICLE_WIDTH, VEHICLE_HEIGHT, VEHICLE_FUEL_TYPE_ID, VEHICLE_NEXT_MAINTENANCE_DATE) VALUES (
	@VEHICLE_SERIAL_NUMBER,
	@VEHICLE_MANUFACTURER_ID,
	@VEHICLE_PRODUCTION_DATE,
	@VEHICLE_NAME,
	@VEHICLE_TYPE_ID,
	@VEHICLE_MASS,
	@VEHICLE_LENGTH,
	@VEHICLE_WIDTH,
	@VEHICLE_HEIGHT,
	@VEHICLE_FUEL_TYPE_ID,
	@VEHICLE_NEXT_MAINTENANCE_DATE);
END

GO

--PROCEDURE PARA INSERS�O DE CENTRAL EL�TRICA NA TABELA 'POWER_PLANTS'. DURANTE ESSA INSERS�O, ESTA � TAMB�M ASSOCIADA �(S) CIDADE(S) ALIMENTADA(S) POR SI
CREATE PROCEDURE SP_INSERT_POWER_PLANTS
@POWER_PLANT_NAME varchar(50),
@POWER_PLANT_COMPANY_ID int,
@POWER_PLANT_TYPE_ID int,
@POWER_PLANT_LOCATION varchar(100),
@POWER_PLANT_MAX_OUTPUT_CAPACITY float,
@POWER_PLANT_STATUS_ID int,
@POWER_PLANT_NEXT_MAINTENANCE_DATE date,
@POWER_PLANT_INSTALLATION_DATE date,
@TARGET_CITIES_ID varchar(20)
AS
BEGIN
	--=======================================================================================================================================================================================================================
	--INSERS�O DA CENTRAL EL�TRICA NA TABELA POWER_PLANTS
	INSERT INTO POWER_PLANTS(POWER_PLANT_NAME, POWER_PLANT_COMPANY_ID, POWER_PLANT_TYPE_ID, POWER_PLANT_LOCATION, POWER_PLANT_MAX_OUTPUT_CAPACITY, POWER_PLANT_STATUS_ID, POWER_PLANT_NEXT_MAINTENANCE_DATE, POWER_PLANT_INSTALLATION_DATE) VALUES(
	@POWER_PLANT_NAME,
	@POWER_PLANT_COMPANY_ID,
	@POWER_PLANT_TYPE_ID,
	@POWER_PLANT_LOCATION,
	@POWER_PLANT_MAX_OUTPUT_CAPACITY,
	@POWER_PLANT_STATUS_ID,
	@POWER_PLANT_NEXT_MAINTENANCE_DATE,
	@POWER_PLANT_INSTALLATION_DATE)

	--=======================================================================================================================================================================================================================

	DECLARE @_POWER_PLANT_ID INT; --ID DA CENTRAL EL�TRICA INSERIDA
	SET @_POWER_PLANT_ID = (SELECT MAX(POWER_PLANT_ID) FROM POWER_PLANTS) --A CENTRAL INSERIDA VAI TER O MAIOR ID DA TABELA (� A MAIS RECENTE)

	DECLARE @TARGET_CITIES_TEMP_TABLE TABLE(splited_str varchar(4)) --TABELA TEMPORARIA PARA GUARDAR OS ID's DAS CIDADES A CONECTAR � CENTRAL
	INSERT INTO @TARGET_CITIES_TEMP_TABLE(splited_str)	(SELECT [value] FROM STRING_SPLIT(@TARGET_CITIES_ID, ',')); --CONVERS�O DE VARCHAR(20) PARA TABLE (SPLIT DA STRING)

	DECLARE @I INT = 1; -- CONTADOR PARA CICLO WHILE
	WHILE @I-1 < (SELECT COUNT(*) FROM @TARGET_CITIES_TEMP_TABLE) -- ESTE CICLO VAI PERCORRER TODOS OS VALORES DA TABELA @TARGET_CITIES_TEMP_TABLE, ENQUANTO @I-1 FOR MENOR QUE O N�MERO DE REGISTOS DESTA
	BEGIN
		DECLARE @_CITY_ID INT; --ID DA CIDADE A LIGAR � CENTRAL EL�TRICA
		SET @_CITY_ID = (SELECT TOP(1) CONVERT(INT, splited_str) FROM @TARGET_CITIES_TEMP_TABLE WHERE @I = CONVERT(INT, splited_str))

		INSERT INTO CITY_REL_POWERPLANTS(CITY_ID, CITY_ENERGY_SOURCE_ID) VALUES(@_CITY_ID, @_POWER_PLANT_ID) --INSERS�O DA LIGA��O DA CIDADE COM A CENTRAL EL�TRICA, NA TABELA QUE AS RELACIONA (CITY_REL_POWERPLANTS)
		SET @I = @I + 1 --INCREMENTO DO CONTADOR @I
	END
	--=======================================================================================================================================================================================================================
END
/*EXEMPLO DE EXECU��O:
EXEC SP_INSERT_POWER_PLANTS @POWER_PLANT_NAME = 'AAAAA',
@POWER_PLANT_COMPANY_ID = 1,
@POWER_PLANT_TYPE_ID = 1,
@POWER_PLANT_LOCATION = 'LOCATION3301',
@POWER_PLANT_MAX_OUTPUT_CAPACITY = 20000,
@POWER_PLANT_STATUS_ID = 1,
@POWER_PLANT_NEXT_MAINTENANCE_DATE = '1990-09-09',
@POWER_PLANT_INSTALLATION_DATE = '1990-09-09',
@TARGET_CITIES_ID = '1,2,3'
*/

GO

--PROCEDURE PARA INSERIR UM NOVO UTILIZADOR
CREATE PROCEDURE SP_INSERT_USER
    @USER_FIRST_NAME VARCHAR(75),
    @USER_LAST_NAME VARCHAR(75),
    @USER_PASSWORD_HASH VARBINARY(255),
    @USER_EMAIL varchar(255),
    @USER_PHONENUMBER varchar(12),
    @USER_PROFILE_PICTURE_PATH varchar(1000),
    @USER_BIRTHDATE DATE,
    @USER_GENDER_ID INT,
    @USER_COUNTRY_ID INT,
    @USER_ADRESS VARCHAR(255),
    @USER_CITIZEN_CARD_NUMBER INT,
    @USER_SALARY FLOAT,
    @USER_BANK_ACCOUNT_NUMBER INT,
    @USER_ACADEMIC_LEVEL_ID INT,
    @USER_JOB_ID INT,
    @USER_LEVEL_ID INT,
	@USER_EMPLOYER_COMPANY_ID INT
AS
BEGIN
	INSERT INTO USERS (
    USER_FIRST_NAME,
    USER_LAST_NAME,
    USER_PASSWORD_HASH,
    USER_EMAIL,
    USER_PHONENUMBER,
    USER_PROFILE_PICTURE_PATH,
    USER_BIRTHDATE,
    USER_GENDER_ID,
    USER_COUNTRY_ID,
    USER_ADRESS,
    USER_CITIZEN_CARD_NUMBER,
    USER_SALARY,
    USER_BANK_ACCOUNT_NUMBER,
    USER_ACADEMIC_LEVEL_ID,
    USER_JOB_ID,
    USER_LEVEL_ID
	) VALUES
	(@USER_FIRST_NAME,
	@USER_LAST_NAME,
	@USER_PASSWORD_HASH,
	@USER_EMAIL,
	@USER_PHONENUMBER,
	@USER_PROFILE_PICTURE_PATH,
	@USER_BIRTHDATE,
	@USER_GENDER_ID,
	@USER_COUNTRY_ID,
	@USER_ADRESS,
	@USER_CITIZEN_CARD_NUMBER,
	@USER_SALARY,
	@USER_BANK_ACCOUNT_NUMBER,
	@USER_ACADEMIC_LEVEL_ID,
	@USER_JOB_ID,
	@USER_LEVEL_ID);

	DECLARE @USER_ID INT;
	SET @USER_ID = (SELECT MAX(USER_ID) FROM USERS (NOLOCK))

	INSERT INTO USER_REL_COMPANY (USER_COMPANY_ID, USER_ID)
	VALUES (@USER_EMPLOYER_COMPANY_ID, @USER_ID)
END